### ISSUE TITLE
Add copyright/license statement on GitHub pages sites

### ISSUE THREAD

**Issue by JeremyBuhler** [ubc-library-rc/rc-workshop-template#7]
The rc-workshop-template repository functions as a remote Jekyll theme: changes to [_layouts/](https://github.com/ubc-library-rc/rc-workshop-template/tree/master/_layouts) affect all Research Commons sites, since the line `remote_theme: ubc-library-rc/rc-workshop-template` is added to each repo's *_config.yml* file during setup.

RC sites may have different licenses. To generate site-specific copyright/license statements I added three custom variables to *_config.yml*

```yaml
# license information for workshop content
license_name: "Creative Commons Attribution 4.0 International License"
license_url: "http://creativecommons.org/licenses/by/4.0/"
license_image_url: "https://i.creativecommons.org/l/by/4.0/88x31.png"
```

I updated  _layouts/default.html to generate site-specific copyright statements from these variables, adjusting if variables are missing (see c052d75 for initial implementation, refined in d196bc1).

The instructions for creating new sites reflect these changes (6518211). To add a copyright statement to an existing RC site add the block above to its *_config.yml* file.
